version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          name: Running tests
          working_directory: ./app
          command: |
            python manage.py test && flake8