version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment: 
            - DB_HOST=localhost
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASSWORD=supersecretpassword

      - image: circleci/postgres:10
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          name: Running tests
          working_directory: ./app
          command: |
            python manage.py test && flake8