version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            pip install docker-compose
      - run:
          name: Running tests
          command: |
            ls
            docker-compose run --rm app sh -c "python manage.py test && flake8"
            
            
      - store_artifacts:
          path: test-reports/
          destination: python_app