version: 2
jobs:
  build:
    docker:
      - image: python:3.8-alpine
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            python manage.py test
            flake8