version: 2
jobs:
  build:
    working_directory: ./app
    docker:
      - image: circleci/python:3.8
        environment: 
            - DB_HOST=localhost
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASSWORD=supersecretpassword

      - image: circleci/postgres:10
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt

      - run: 
          command: |
            sudo mkdir -m 0755 -p /vol/web/media
            sudo mkdir -m 0755 -p /vol/web/static
      - run:
          name: Running tests
          command: |
            python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py test && flake8