version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            ls
            python ./app/manage.py test && flake8
            
            
      - store_artifacts:
          path: test-reports/
          destination: python_app