version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            pip install docker-compose
            pip install docker-client
      - run:
          name: Running tests
          command: |
            ls
            docker-compose run app sh -c "python manage.py test && flake8"
            
            
      - store_artifacts:
          path: test-reports/
          destination: python_app